### ISSUE TITLE
The roles are not downloaded

### ISSUE THREAD

**Issue by merito** [devopsysadmin/ansible-bundle#12]
Hi,

I try to run command `ansible-bundle -v playbook.yml` but the output says
```
[INFO] Getting common (master) ...
[INFO] Getting gui (master) ...

Running playbook
No config file found; using defaults
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available

ERROR! the role 'common' was not found in /home/xxx/xxx/test/ansible/roles:/etc/ansible/roles:/home/xxx/xxx/test/ansible

The error appears to have been in '/home/xxx/xxx/test/ansible/playbook.yml': line 4, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - common
      ^ here
```

playbook.yml
```
---
- hosts: all
  roles:
    - common
    - gui
```

bundle.cfg
```
[bundle]
url='git@192.168.1.1:abc/my_roles.git'
```

The repo structure is
```
 $ tree my_roles -L 2
my_roles
├── test2
│   ├── files
│   ├── handlers
│   └── tasks
├── common
│   ├── handlers
│   └── tasks
└── gui
    ├── files
    └── tasks
```

I know I need `--connection=local` to run this playbook locally, but there are no roles downloaded to roles directory. It looks like
```
 $ tree roles               
roles
└── unversioned

1 directory, 0 files
```

I've tried with 0.5.1, 0.5.2 and current develop branch, still the same.

Maybe I'm doing it wrong, the example section of project README is only a stub, then please correct me or maybe this is a bug, I don't know, verbose in debug mode doesn't say anything.

Thanks for developing this project, it looks very interesting to me.
Regards

**Comment by devopsysadmin** [comment]
Hi @merito ! Thanks for giving ansible-bundle a try.
In your bundle.cfg file, your url points to a specific repository (abc/my_roles.git) when the bundle expects a project url to find roles. I mean, each role is, in fact, a repository, and the url is a main directory/folder/project where the bundle will search them.

I'll try to explain better: Given the main directory you provided, bundle expects to find `192.168.1.1:abc/my_roles/common.git` and `192.168.1.1:abc/my_roles/gui.git`

I think I might work more in the example section to be more clarifying.

Regards and thanks again for the feedback 😃

**Comment by merito** [comment]
Yeah, it makes sense. Using one repository it can't download only needed roles. So, it is not suitable for my needs. You can keep this issue open if you want to remember about expanding examples or close it.
Thank you
