### ISSUE TITLE
The base path while getting includes dependencies does not follows the same rules than ansible itself

### ISSUE THREAD

**Issue by pablerass** [devopsysadmin/ansible-bundle#8]
When running something like `ansible-bundle playbooks/play.yml`, if `play.yml` contains includes, it can not be executed.

If its content is something like `- include: subplay.yml`, _ansible-bundle_ will return the error:
```
[ERROR] File subplay.yml not found
```

If you modify the playbook to something like `-include: playbooks/subplay.yml`, _asible-playbook_ itself will not find the playbook and return:

```
Running playbook
ERROR! the file_name '.../playbooks/playbooks/subplay.yml' does not exist, or is not readable
```

**Comment by devopsysadmin** [comment]
Hi, @pablerass, and sorry for taking SO long.

I think I solved it in current development version by entering into the _dirname_ of the playbook. Take a look and please reopen if it doesn't.

Thanks! 😃
